2025-03-23 22:00:16,739 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - server heartbeat timeout set to 600
2025-03-23 22:00:16,828 - CoreCell - INFO - server: creating listener on grpc://0:443
2025-03-23 22:00:16,857 - CoreCell - INFO - server: created backbone external listener for grpc://0:443
2025-03-23 22:00:16,857 - ConnectorManager - INFO - 2318942: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2025-03-23 22:00:16,858 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:6734] is starting
2025-03-23 22:00:17,359 - CoreCell - INFO - server: created backbone internal listener for tcp://localhost:6734
2025-03-23 22:00:17,359 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE grpc://0:443] is starting
2025-03-23 22:00:17,362 - FederatedServer - INFO - max_reg_duration=60.0
2025-03-23 22:00:17,368 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - deployed FLARE Server.
2025-03-23 22:00:17,373 - MPM - ERROR - Execute exception: PermissionError: [Errno 13] Permission denied
2025-03-23 22:00:17,374 - MPM - ERROR - Traceback (most recent call last):
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/f3/mpm.py", line 154, in run
    rc = main_func(**kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/server/server_train.py", line 113, in main
    admin_server = create_admin_server(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/utils.py", line 81, in create_admin_server
    admin_server = FedAdminServer(
                   ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/server/admin.py", line 175, in __init__
    AdminServer.__init__(
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/hci/server/hci.py", line 180, in __init__
    self.server_bind()
  File "/usr/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

2025-03-23 22:00:19,363 - MPM - WARNING - #### MPM: still running thread Thread-3 (client_cleanup)
2025-03-23 22:00:19,363 - MPM - WARNING - #### MPM: still running thread Thread-5 (_start_job_runner)
2025-03-23 22:00:19,363 - MPM - WARNING - #### MPM: still running thread Thread-6 (_job_complete_process)
2025-03-23 22:00:19,363 - MPM - INFO - MPM: Good Bye!
2025-03-23 22:00:21,756 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - server heartbeat timeout set to 600
2025-03-23 22:00:21,844 - CoreCell - INFO - server: creating listener on grpc://0:443
2025-03-23 22:00:21,874 - CoreCell - INFO - server: created backbone external listener for grpc://0:443
2025-03-23 22:00:21,874 - ConnectorManager - INFO - 2319039: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2025-03-23 22:00:21,875 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:1378] is starting
2025-03-23 22:00:22,376 - CoreCell - INFO - server: created backbone internal listener for tcp://localhost:1378
2025-03-23 22:00:22,376 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE grpc://0:443] is starting
2025-03-23 22:00:22,378 - FederatedServer - INFO - max_reg_duration=60.0
2025-03-23 22:00:22,385 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - deployed FLARE Server.
2025-03-23 22:00:22,390 - MPM - ERROR - Execute exception: PermissionError: [Errno 13] Permission denied
2025-03-23 22:00:22,391 - MPM - ERROR - Traceback (most recent call last):
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/f3/mpm.py", line 154, in run
    rc = main_func(**kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/server/server_train.py", line 113, in main
    admin_server = create_admin_server(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/utils.py", line 81, in create_admin_server
    admin_server = FedAdminServer(
                   ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/server/admin.py", line 175, in __init__
    AdminServer.__init__(
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/hci/server/hci.py", line 180, in __init__
    self.server_bind()
  File "/usr/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

2025-03-23 22:00:24,379 - MPM - WARNING - #### MPM: still running thread Thread-3 (client_cleanup)
2025-03-23 22:00:24,379 - MPM - WARNING - #### MPM: still running thread Thread-5 (_start_job_runner)
2025-03-23 22:00:24,379 - MPM - WARNING - #### MPM: still running thread Thread-6 (_job_complete_process)
2025-03-23 22:00:24,380 - MPM - INFO - MPM: Good Bye!
2025-03-23 22:00:26,786 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - server heartbeat timeout set to 600
2025-03-23 22:00:26,874 - CoreCell - INFO - server: creating listener on grpc://0:443
2025-03-23 22:00:26,903 - CoreCell - INFO - server: created backbone external listener for grpc://0:443
2025-03-23 22:00:26,903 - ConnectorManager - INFO - 2319136: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2025-03-23 22:00:26,904 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:29880] is starting
2025-03-23 22:00:27,405 - CoreCell - INFO - server: created backbone internal listener for tcp://localhost:29880
2025-03-23 22:00:27,405 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE grpc://0:443] is starting
2025-03-23 22:00:27,406 - FederatedServer - INFO - max_reg_duration=60.0
2025-03-23 22:00:27,413 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - deployed FLARE Server.
2025-03-23 22:00:27,418 - MPM - ERROR - Execute exception: PermissionError: [Errno 13] Permission denied
2025-03-23 22:00:27,419 - MPM - ERROR - Traceback (most recent call last):
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/f3/mpm.py", line 154, in run
    rc = main_func(**kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/server/server_train.py", line 113, in main
    admin_server = create_admin_server(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/utils.py", line 81, in create_admin_server
    admin_server = FedAdminServer(
                   ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/server/admin.py", line 175, in __init__
    AdminServer.__init__(
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/hci/server/hci.py", line 180, in __init__
    self.server_bind()
  File "/usr/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

2025-03-23 22:00:29,408 - MPM - WARNING - #### MPM: still running thread Thread-3 (client_cleanup)
2025-03-23 22:00:29,408 - MPM - WARNING - #### MPM: still running thread Thread-5 (_start_job_runner)
2025-03-23 22:00:29,409 - MPM - WARNING - #### MPM: still running thread Thread-6 (_job_complete_process)
2025-03-23 22:00:29,409 - MPM - INFO - MPM: Good Bye!
2025-03-23 22:00:31,768 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - server heartbeat timeout set to 600
2025-03-23 22:00:31,856 - CoreCell - INFO - server: creating listener on grpc://0:443
2025-03-23 22:00:31,888 - CoreCell - INFO - server: created backbone external listener for grpc://0:443
2025-03-23 22:00:31,888 - ConnectorManager - INFO - 2319233: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2025-03-23 22:00:31,889 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:59549] is starting
2025-03-23 22:00:32,390 - CoreCell - INFO - server: created backbone internal listener for tcp://localhost:59549
2025-03-23 22:00:32,390 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE grpc://0:443] is starting
2025-03-23 22:00:32,396 - FederatedServer - INFO - max_reg_duration=60.0
2025-03-23 22:00:32,398 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - deployed FLARE Server.
2025-03-23 22:00:32,403 - MPM - ERROR - Execute exception: PermissionError: [Errno 13] Permission denied
2025-03-23 22:00:32,404 - MPM - ERROR - Traceback (most recent call last):
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/f3/mpm.py", line 154, in run
    rc = main_func(**kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/server/server_train.py", line 113, in main
    admin_server = create_admin_server(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/utils.py", line 81, in create_admin_server
    admin_server = FedAdminServer(
                   ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/server/admin.py", line 175, in __init__
    AdminServer.__init__(
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/hci/server/hci.py", line 180, in __init__
    self.server_bind()
  File "/usr/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

2025-03-23 22:00:34,393 - MPM - WARNING - #### MPM: still running thread Thread-3 (client_cleanup)
2025-03-23 22:00:34,393 - MPM - WARNING - #### MPM: still running thread Thread-5 (_start_job_runner)
2025-03-23 22:00:34,393 - MPM - WARNING - #### MPM: still running thread Thread-6 (_job_complete_process)
2025-03-23 22:00:34,393 - MPM - INFO - MPM: Good Bye!
2025-03-23 22:00:36,795 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - server heartbeat timeout set to 600
2025-03-23 22:00:36,896 - CoreCell - INFO - server: creating listener on grpc://0:443
2025-03-23 22:00:36,926 - CoreCell - INFO - server: created backbone external listener for grpc://0:443
2025-03-23 22:00:36,926 - ConnectorManager - INFO - 2319330: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2025-03-23 22:00:36,926 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:4671] is starting
2025-03-23 22:00:37,427 - CoreCell - INFO - server: created backbone internal listener for tcp://localhost:4671
2025-03-23 22:00:37,427 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE grpc://0:443] is starting
2025-03-23 22:00:37,433 - FederatedServer - INFO - max_reg_duration=60.0
2025-03-23 22:00:37,435 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - deployed FLARE Server.
2025-03-23 22:00:37,440 - MPM - ERROR - Execute exception: PermissionError: [Errno 13] Permission denied
2025-03-23 22:00:37,441 - MPM - ERROR - Traceback (most recent call last):
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/f3/mpm.py", line 154, in run
    rc = main_func(**kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/server/server_train.py", line 113, in main
    admin_server = create_admin_server(
                   ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/app/utils.py", line 81, in create_admin_server
    admin_server = FedAdminServer(
                   ^^^^^^^^^^^^^^^
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/private/fed/server/admin.py", line 175, in __init__
    AdminServer.__init__(
  File "/home/ubuntu/nv/lib/python3.12/site-packages/nvflare/fuel/hci/server/hci.py", line 180, in __init__
    self.server_bind()
  File "/usr/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

2025-03-23 22:00:39,430 - MPM - WARNING - #### MPM: still running thread Thread-3 (client_cleanup)
2025-03-23 22:00:39,431 - MPM - WARNING - #### MPM: still running thread Thread-5 (_start_job_runner)
2025-03-23 22:00:39,431 - MPM - WARNING - #### MPM: still running thread Thread-6 (_job_complete_process)
2025-03-23 22:00:39,431 - MPM - INFO - MPM: Good Bye!
2025-03-23 22:05:07,762 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - server heartbeat timeout set to 600
2025-03-23 22:05:07,863 - CoreCell - INFO - server: creating listener on grpc://0:443
2025-03-23 22:05:07,893 - CoreCell - INFO - server: created backbone external listener for grpc://0:443
2025-03-23 22:05:07,894 - ConnectorManager - INFO - 2319563: Try start_listener Listener resources: {'secure': False, 'host': 'localhost'}
2025-03-23 22:05:07,894 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00002 PASSIVE tcp://0:48903] is starting
2025-03-23 22:05:08,395 - CoreCell - INFO - server: created backbone internal listener for tcp://localhost:48903
2025-03-23 22:05:08,395 - nvflare.fuel.f3.sfm.conn_manager - INFO - Connector [CH00001 PASSIVE grpc://0:443] is starting
2025-03-23 22:05:08,396 - FederatedServer - INFO - max_reg_duration=60.0
2025-03-23 22:05:08,404 - nvflare.private.fed.app.deployer.server_deployer.ServerDeployer - INFO - deployed FLARE Server.
2025-03-23 22:05:08,407 - nvflare.fuel.f3.drivers.grpc_driver.Server - INFO - added secure port at 0.0.0.0:443
2025-03-23 22:05:08,409 - nvflare.fuel.hci.server.hci - INFO - Starting Admin Server 140.110.139.139 on Port 80
2025-03-23 22:05:08,409 - root - INFO - Server started
2025-03-23 22:05:14,404 - ServerState - INFO - Got the primary sp: 140.110.139.139 fl_port: 443 SSID: ebc6125d-0a56-4688-9b08-355fe9e4d61a. Turning to hot.
